### PR TITLE
KPP version 2.4.0 release

### PR DESCRIPTION
**Pull request by yantosca**
@RolfSander has merged the MECCA branch of development into the dev branch.  We can now consider releasing KPP 2.4.0.

I have updated the CHANGELOG.md and the version number in gdata.h accordingly.

### CODE REVIEW

**Comment by RolfSander** [comment]
Thanks, @yantosca, for preparing version 2.4.0!

I would like to do more testing inside my MECCA environment before 2.4.0
is released. Can we start with calling the current version 2.4.0-rc.0? I
can create a temporary "release" branch for my tests. That way you can
continue with merging the GC_updates into dev (PR #28) and don't have to
wait for me.

(btw: note that the CI checks failed already because your latest bug fix
for kpp_lsode.f90 is only in add-geos-chem-updates but not yet in dev)

**Comment by yantosca** [comment]
The CI failures are now fixed in commit 76890098ddc972b300d403f357240a1b6b0ed30d.  This was because the `int/kpp_lsode.f90` integrator did not declare real variable `TOLD`, which caused a compile-time error.

**Comment by RolfSander** [comment]
I made a few small changes:

- I don't think RTOLS is needed (gen.c).

- My comments about index numbers was incorrect, so I simplified it now (code_f90.c).

**Review by RolfSander — APPROVED** [review]
I'm done with my tests. KPP 2.4.0 works fine in our MECCA chemistry
model. I'm happy to merge dev into main now.

**Comment by yantosca** [comment]
Thanks @RolfSander, go ahead and merge.  Great job!

**Pull request merged**
