### PR TITLE
ReadTheDocs documentation for KPP 2.5.0

### PR DESCRIPTION
**Pull request by yantosca**
I've made several updates to the ReadTheDocs documentation and I think we are now in a pretty good place to releasing KPP 2.5.0.  Please take a look at https://kpp.readthedocs.io and let me know if you have any suggested changes.

### CODE REVIEW

**Comment by RolfSander** [comment]
Thanks, this must have been a lot of work! I will go through the
documentation and leave a comment here whenever I find something...

**Comment by RolfSander** [comment]
00_revision_history.html:

- for KPP 2.2.3, add:

  - There were more new integrators: (kpp_)dvode.f90, runge_kutta.f90,
    runge_kutta_adj.f90, runge_kutta_tlm.f90, sdirk_adj.f90,
    sdirk_tlm.f90

  - new Rosenbrock method Rang3

  - Several vector and array functions from BLAS (WCOPY, WAXPY, ...)
    were replaced by Fortran 90 expressions.

- I think the introductory sentence for the changes in KPP 2.1 can be
  deleted: "This user manual describes recently added features of KPP as
  well as those which have been available for a longer period. Here we
  give an overview about the recent changes:"

**Comment by RolfSander** [comment]
01_installation.html:

- broken link in "Clone the KPP source code from the KPP Github
  repository:"

- maybe we should also mention gcc as a dependency?

- "If you use the bash shell, edit ??? and add:" -> file name missing

- "You can add the following statements..." -> the ABOVE statements?

- "If necessary, edit and enter the name of your C compiler in
  src/Makefile." -> this should be `Makefile.defs`

**Comment by RolfSander** [comment]
02_running_kpp_sample_mech.html:

- "In this paper we will refer to this name as ROOT." -> Maybe "here"
  instead of "In this paper".

- "The #INTEGRATOR and #INTFILE commands select a specific numerical
  integration routine" -> I don't think we need to mention `#INTFILE`
  here. The user only needs `#INTEGRATOR`.

- "is the normalized sunlight intensity" -> The word "SUN"is missing.

**Comment by RolfSander** [comment]
04_input_for_kpp.html:

- "An exception is the file atoms, which has no suffix." -> Maybe we
  should rename this file to `atoms.kpp`? I don't see a good reason why
  it doesn't have a suffix yet.

- "KPP accepts only one of these files as input, but using the command,
  code from separate files can be combined." -> The word `#INCLUDE` is
  missing.

- "i.e. when another sign occurs at the beginning of a line." -> `#` is
  missing.

- Hmm, there seem to be many more cases where the command names like
  `#SOMETHING` have disappeared from the manual...

**Comment by RolfSander** [comment]
>> Maybe we should rename this file to atoms.kpp?

> Agreed

OK, I'll take care of this.

> Yes, pandoc somehow didn't bring over text beginning with #.

I noticed that the same problem also occurs for text without `#`, for
example the "IGNORE" is missing in the description of `#CHECK`:

"The _____ atom can also be used to control mass balance checking."

Maybe the problem is that pandoc could not treat the self-defined
command `\code{...}` in the LaTeX file of the user manual.

**Comment by RolfSander** [comment]
> Agreed. We should rename that. I can do that in the docs branch.

Oops. I overlooked that you volunteered to do this...

Yes, please go ahead if you want...

**Comment by yantosca** [comment]
> > Agreed. We should rename that. I can do that in the docs branch.
> 
> Oops. I overlooked that you volunteered to do this...
> 
> Yes, please go ahead if you want...

atoms is now atoms.kpp in commit 0098c276010ad65ec225f1e08fb7a5bbfa84d16e

**Comment by yantosca** [comment]
@RolfSander, I think I've fixed most of the remaining issues in commits https://github.com/KineticPreProcessor/KPP/pull/41/commits/1597faf8b6eb8f96cc86f4b122cda72540b1d8f4, https://github.com/KineticPreProcessor/KPP/pull/41/commits/6c563cd04b7f6f24b584ee2c1c249ef303b6de87, and https://github.com/KineticPreProcessor/KPP/pull/41/commits/7bca904e511e6055f148b98ba0d658c7609ac13c.

Running KPP with an example mechanism has also been updated to list things more in a step-by-step fashion.

**Comment by msl3v** [comment]
> * "An exception is the file atoms, which has no suffix." -> Maybe we
>       should rename this file to `atoms.kpp`? I don't see a good reason why
>       it doesn't have a suffix yet.

On "Input for KPP", should #INCLUDE atoms.kpp be #INCLUDE atoms? or is "atoms" being renamed to "atoms.kpp"?

**Comment by msl3v** [comment]
04_input_for_kpp.html
Suggest rewriting 

"The example below shows how the concentration of can be replaced by the sum of concentrations for and which is considered to be a single variable. At the end of the integration, the concentration of is computed by substraction from the lumped variable."

to

"In the example below, species NO and NO2 are summed and treated as a single lumped variable, NO2. Following integration, the individual species concentrations are recomputed from the lumped variable."

**Comment by msl3v** [comment]
04_input_for_kpp.html
Can an example of #DECLARE be provided?

(There's a lot of KPP I didn't know about!)

**Comment by RolfSander** [comment]
> Can an example of #DECLARE be provided?

I haven't used `#DECLARE` myself but I think the idea is this: If
`NSPEC` is a Fortran PARAMETER, a clever compiler can insert its value
into `C(NSPEC)` at compile-time. A stupid compiler will look up the
value of `NSPEC` every time it encounters `C(NSPEC)`. If NSPEC=7, KPP
can directly generate `C(7)` for those stupid compilers.

**Comment by msl3v** [comment]
Very good explanation
It seems like a lot of thought went into getting inefficiencies ironed out.

**Comment by RolfSander** [comment]
> Running KPP with an example mechanism has also been updated to list
> things more in a step-by-step fashion.

Thanks, this section has improved a lot!

(I fixed a small error about `SUN`)

**Comment by RolfSander** [comment]
Another idea regarding `atoms.kpp`: I would like to add `Pls` and `Min`
as "pseudo-atoms" here. If these are used in the elemental composition
of ions in the `*.spc` file, it becomes possible to check the charge
balance of the equations.

In MECCA, we use this for ions in the aqueous phase and also for ions in
the upper atmosphere.

**Comment by yantosca** [comment]
@msl3v: I added your sample text to `04_input_for_kpp.rst`, and added a better description of the `#DECLARE` command.  I rewrote the `02_running_kpp_sample_mech.rst` to remove the commands to copy the files over to the example folder.  I also reordered the explanation of each command in the example.

**Comment by yantosca** [comment]
@RolfSander @msl3v let me know when the doc is good enough to move to release 2.5.0 ...

**Comment by RolfSander** [comment]
> let me know when the doc is good enough to move to release 2.5.0 ...

We still have to improve the documentation but that shouldn't stop us
from releasing 2.5.0 now.

Since the documentation is now online, people will always find the
latest version at kpp.readthedocs.io, even if they have 2.5.0 locally on
their computers.

**Review by RolfSander — APPROVED** [review]

**Comment by yantosca** [comment]
Great!  I'll move to release later today.

**Pull request merged**
