### PR TITLE
FIX must be the 2nd argument passed to FUN in int/feuler.f90 (plus doc updates)

### LINKED ISSUE #60: [BUG/ISSUE] FIX must be the 2nd argument passed to FunTemplate in int/feuler.f90-
While testing the carboncycle simulation in GEOS-Chem (which uses the Forward-Euler integrator, `int/feuler.f90`), I was getting negative concentrations that were hard to pin down.  Long story short, I traced this to this line of code:

https://github.com/KineticPreProcessor/KPP/blob/d690142f8a7e80e79ecb8ba203b004dbeee63afb/int/feuler.f90#L199-L200

but the generated `Fun` routine always takes the vector of fixed species concentrations (`FIX`) as the 2nd argument:

```F90
SUBROUTINE Fun ( V, F, RCT, Vdot, Aout, Vdotout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
```
This led to the F dummy-argument variable being set to a random negative number and propagating negatives through the code.

The fix is just to change
```F90
CALL Fun( Y, VAR, RCONST, Ydot ) 
```
to
```F90
CALL Fun( Y, FIX, RCONST, Ydot ) 
```
in `int/feuler.f90`.  I will submit a PR soon for this for KPP 3.0.0.

### PR DESCRIPTION
**Pull request by yantosca**
This is the corresponding PR to #60.  Also, documentation has been updated to denote this will be KPP 3.0.0-rc.4.

Closes #60

### CODE REVIEW

**Comment by RolfSander** [comment]
AFAICS, this is fine. However, maybe Mike also wants to comment, as feuler.f90 is his code?

**Comment by msl3v** [comment]
This fix is correct. VAR was included erroneously as an argument to FUN() in feuler.f90.

**Comment by yantosca** [comment]
@msl3v @jimmielin @RolfSander: could one of you approve the PR?  I can't do it as the author.  Then I can merge & release.  Thanks!

**Comment by yantosca** [comment]
Also note: GitHub allows you to automatically generate release notes based on the comments in the logs from each PR.  So it's important that even simple fixes like this go thru a PR.

**Review by jimmielin — APPROVED** [review]

**Comment by jimmielin** [comment]
Thanks Bob, approved!

**Comment by msl3v** [comment]
Wasn't listed as a reviewer. Could I still have approved this? (I looked but didn't see that it was possible)

**Comment by yantosca** [comment]
My bad, @msl3v.  I should have made you a reviewer.

**Pull request merged**
