### PR TITLE
Add code from #INLINE F90_RCONST_USE at the top of the UPDATE_RCONST subroutine

### LINKED ISSUE #119: [BUG/ISSUE] Wrong placement of YIN argument in subroutine Update_Rconst
In the `dev` branch, when we create the `*Rates.F90` file, the `YIN` argument definition statements in routine `Update_Rconst` are placed before the `INLINED_RCONST` statement.  If a `USE` statement is included in the `INLINED_RCONST` section, then this will generate code such as this:
```F90
SUBROUTINE Update_RCONST ( YIN )

! YIN - Optional input concentrations of variable species
  REAL(kind=dp), OPTIONAL :: YIN(NVAR)

! Y - Concentrations of species (local)
  REAL(kind=dp) :: Y(NSPEC)

! Ensure local Y array is filled with variable and constant concentrations
  Y(1:NSPEC) = C(1:NSPEC)

! Update local Y array if variable concentrations are provided
  if (present(YIN)) Y(1:NVAR) = YIN(1:NVAR)


! Begin INLINED RCONST


  ! Inline an include file containing rate law definitions, which
  ! will be inserted directly into subroutine Update_Rconst().
  ! This is necessary as a workaround for KPP not being able to
  ! include very large files ( > 200000 chars) directly.
  !  -- Bob Yantosca (11 Jun 2021)
  USE fullchem_RateLawFuncs

! End INLINED RCONST
```
This will generate an error such as:
```console
gfortran -cpp -O   -c gckpp_Precision.F90
gfortran -cpp -O   -c gckpp_Parameters.F90
gfortran -cpp -O   -c gckpp_Global.F90
gfortran -cpp -O   -c gckpp_JacobianSP.F90
gfortran -cpp -O   -c gckpp_Jacobian.F90
gfortran -cpp -O   -c gckpp_Function.F90
gfortran -cpp -O   -c rateLawUtilFuncs.F90
gfortran -cpp -O   -c fullchem_RateLawFuncs.F90
gfortran -cpp -O   -c gckpp_Rates.F90
gckpp_Rates.F90:439:27:

  439 |   USE fullchem_RateLawFuncs
      |                           1
Error: Unexpected USE statement at (1)
make: *** [Makefile:163: gckpp_Rates.o] Error 1
Failed to build the 'kpp_executable.exe' file!  Aborting...
```
This is because the USE statement must come before any variable declarations or executable statements.

The fix is simple, to place the `INLINED_RCONST` section first before adding the `YIN` variable declarations.  I can push a fix.

Currently this only affects code in the `dev` branch but not in `main`.

Tagging @jimmielin @RolfSander

### PR DESCRIPTION
**Pull request by yantosca**
This is the companion PR to #119.  In that issue we described how the `UPDATE_RCONST` routine was generated such that a USE statement in `INLINED RCONST`:

```F90
SUBROUTINE Update_RCONST ( YIN )

! YIN - Optional input concentrations of variable species
  REAL(kind=dp), OPTIONAL :: YIN(NVAR)

! Y - Concentrations of species (local)
  REAL(kind=dp) :: Y(NSPEC)

! Ensure local Y array is filled with variable and constant concentrations
  Y(1:NSPEC) = C(1:NSPEC)

! Update local Y array if variable concentrations are provided
  if (present(YIN)) Y(1:NVAR) = YIN(1:NVAR)


! Begin INLINED RCONST


  ! Inline an include file containing rate law definitions, which
  ! will be inserted directly into subroutine Update_Rconst().
  ! This is necessary as a workaround for KPP not being able to
  ! include very large files ( > 200000 chars) directly.
  !  -- Bob Yantosca (11 Jun 2021)
  USE fullchem_RateLawFuncs

! End INLINED RCONST
```
could cause a compiler error due to the `USE` statement not being first in the subroutine.

This PR has edited the `GenerateUpdateRconst` routine in `src/gen.c` to do the following:
1. Manually write the `SUBROUTINE UPDATE_RCONST ( YIN )` line
2. Inline code from the `#INLINE F90_RCONST_USE` section
3. Declare `YIN` optional argument and `Y` local variable
4. Copy values of `YIN` to `Y` (if necessary)
5. Inline code from the `#INLINE F90_RCONST` section
6. Manually write the `END SUBROUTINE UPDATE_RCONST` line

This will only affect the F90 output, which now looks like this:
```F90
SUBROUTINE Update_RCONST ( YIN )

! Begin INLINED RCONST - F90 USE STATEMENTS


  ! Inline an include file containing rate law definitions, which
  ! will be inserted directly into subroutine Update_Rconst().
  ! This is necessary as a workaround for KPP not being able to
  ! include very large files ( > 200000 chars) directly.
  !  -- Bob Yantosca (11 Jun 2021)
  USE fullchem_RateLawFuncs

! End INLINED RCONST - F90 USE STATEMENTS

! YIN - Optional input concentrations of variable species
  REAL(kind=dp), OPTIONAL :: YIN(NVAR)

! Y - Concentrations of species (local)
  REAL(kind=dp) :: Y(NSPEC)

! Ensure local Y array is filled with variable and constant concentrations
  Y(1:NSPEC) = C(1:NSPEC)

! Update local Y array if variable concentrations are provided
  if (present(YIN)) Y(1:NVAR) = YIN(1:NVAR)




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = ...
```
which now compiles properly:
```console
KPP has successfully created the model "gckpp".

gfortran -cpp -O  -c gckpp_Precision.F90
gfortran -cpp -O  -c gckpp_Parameters.F90
gfortran -cpp -O  -c gckpp_Global.F90
gfortran -cpp -O  -c gckpp_JacobianSP.F90
gfortran -cpp -O  -c gckpp_Jacobian.F90
gfortran -cpp -O  -c gckpp_Function.F90
gfortran -cpp -O  -c rateLawUtilFuncs.F90
gfortran -cpp -O  -c fullchem_RateLawFuncs.F90
gfortran -cpp -O  -c gckpp_Rates.F90
gfortran -cpp -O  -c gckpp_Monitor.F90
gfortran -cpp -O  -c gckpp_Util.F90
gfortran -cpp -O  -c gckpp_LinearAlgebra.F90
gckpp_LinearAlgebra.F90:3455:46:

 3455 |       IF (incX .EQ. incY) IF (incX-1) 5,20,60
      |                                              1
Warning: Fortran 2018 deleted feature: Arithmetic IF statement at (1)
make: Circular gckpp_Model.o <- gckpp_Model.o dependency dropped.
gfortran -cpp -O  -c gckpp_Initialize.F90
make: Circular gckpp_Integrator.o <- gckpp_Model.o dependency dropped.
gfortran -cpp -O  -c gckpp_Integrator.F90
gfortran -cpp -O  -c gckpp_Model.F90
gfortran -cpp -O  -c kpp_standalone_init.F90
gfortran -cpp -O  -c kpp_standalone.F90
gfortran -cpp -O  kpp_standalone.F90 gckpp_Integrator.o kpp_standalone_init.o gckpp_Precision.o gckpp_Parameters.o gckpp_Global.o      gckpp_JacobianSP.o    gckpp_Jacobian.o gckpp_Function.o    gckpp_Rates.o   gckpp_Util.o   gckpp_Monitor.o fullchem_RateLawFuncs.o rateLawUtilFuncs.o gckpp_LinearAlgebra.o    gckpp_Model.o gckpp_Initialize.o    -o kpp_standalone.exe
```

Closes #119

### CODE REVIEW

**Comment by RolfSander** [comment]
We have this problem in the dev branch since `SUBROUTINE Update_RCONST`
has a parameter. Unfortunately, I don't think that the solution covers
all cases. In our [docs](https://kpp.readthedocs.io/en/stable/using_kpp/04_input_for_kpp.html#f90-rconst), we present two possibilities for using `INLINE F90_RCONST`:

```
#INLINE F90_RCONST
  USE MyRateFunctionModule
#ENDINLINE
```

and

```
#INLINE F90_RCONST
  k_DMS_OH = 1.E-9*EXP(5820./temp)*C(ind_O2)/ &
    (1.E30+5.*EXP(6280./temp)*C(ind_O2))
#ENDINLINE
```

The solution in this PR works fine in the first case when the
`F90_RCONST` block contains only `USE` statements. However, after
applying this PR, the code fails when variables are defined directly, as
in the second case.

A possible solution could be to create a separate inlined type
called `F90_RCONST_USE` where the user can place `USE` statements.

**Review by RolfSander — CHANGES_REQUESTED** [review]
Maybe create `F90_RCONST_USE`?

**Comment by yantosca** [comment]
@RolfSander: Yes, I thought of that after I went home after making the PR.  I'll try to add a separate line for USE statements.  Thanks for the feedback!

**Comment by yantosca** [comment]
@RolfSander: I modified the code in bd4745f  so that we place `#INLINE F90_RCONST_USE` at the top of the subroutine while leaving the `#INLINE F90_RCONST` untouched.

**Review by RolfSander — APPROVED** [review]
Thanks, @yantosca for coding this so quickly! The code looks good, I
just have a few minor comments:

1) It would be good to mention the new inline type also in
   `docs/source/using_kpp/04_input_for_kpp.rst`.

2) You've added `/examples/mcm*/*.exe` to `.gitignore`. I wonder if
   there are any executable `*.exe` files at all that we want in our
   repo. If not, maybe we can exclude all `*.exe` files in `.gitignore`?

3) Currently, the following comment is inserted into the KPP-generated
   files:

   `Begin INLINED RCONST - F90 USE STATEMENTS`

   Maybe it would be better to rename this to:

   `Begin inlined code from F90_RCONST_USE`

   Using the term "`F90_RCONST_USE`" verbatim here would facilitate
   finding the inlined code in the KPP-generated files. Similarly, I
   think it would be good if the name appears verbatim also in the
   comments created for the other `F90_*` inline types.

If you agree but don't have the time to implement it now, let me know!

**Comment by yantosca** [comment]
Thanks @RolfSander.  I will make those edits before I merge the branch.  Easy enough!

**Comment by yantosca** [comment]
Minor fixes based on your suggestions added in commit 2f97825

**Pull request merged**
