### PR TITLE
Bring over main branch changes from geoschem/KPP

### PR DESCRIPTION
**Pull request by laestrada**
@yantosca This PR contains the code updates from the main branch of geoschem/KPP. I looked over the changes and didn't see any code that looked too specific to GC -- the assumption being that any GC specific code we would need to develop some logic to turn those features on or off. However, I think you may be a better judge in that regard than I am.

### CODE REVIEW

**Review by yantosca — COMMENTED** [review]
Thanks @laestrada.  My thoughts are below.  Also tagging @RolfSander and @msl3v who are maybe a bit more familiar with the innards of KPP than me:

  1. I'm not sure if changing the FLEX_LIB_DIR from /usr/lib to /usr/lib64 will break anything.  I think we did that because that's where it is on Cannon.
  2. Bringing in the $OMP THREADPRIVATE function prototypes and functions should be OK. But I wonder if we should try to have a switch whether to toggle that or not.   Also in util/blas.F90 maybe there should be a toggle to either write or not write the THREADPRIVATE setting.
  3. The code for MAX_FAMILIES and MAX_MEMBERS (in gen.c) was added by Mike Long for GEOS-Chem.  This will probably need to be blocked out with some kind of logic if people don't want to use it.
  4. We probably will need to increase the settings of MAX_SPECIES, MAX_VALUES, and MAX_INLINE.

So this PR brings in a lot of the updates that @msl3v added to KPP on top of the base version 2.2.3.  At the time we weren't concerned with toggling stuff on/off but now I think we have to be a little more careful.

**Review by yantosca — COMMENTED** [review]
Actually there is a toggle for the KPP families at the top of the .kpp file.  So I think this may not need any work.  I think if this is omitted from the .kpp file it isn't added in.
```#FAMILIES
POx : O3 + NO2 + 2NO3 + PAN + PPN + MPAN + HNO4 + 3N2O5 + HNO3 + BrO + HOBr + BrNO2 + 2BrNO3 + MPN + ETHLN + MVKN + MCRHN + MCRHNB + PROPNN + R4N2 + PRN1 + PRPN + R4N1 + HONIT + MONITS + MONITU + OLND + OLNN + IHN1 + IHN2 + IHN3 + IHN4 + INPB + INPD + ICN + 2IDN + ITCN + ITHN + ISOPNOO1 + ISOPNOO2 + INO2B + INO2D + INA + IDHNBOO + IDHNDOO1 + IDHNDOO2 + IHPNBOO + IHPNDOO + ICNOO + 2IDNOO + MACRNO2 + ClO + HOCl + ClNO2 + 2ClNO3 + 2Cl2O2 + 2OClO + O + O1D + IO + HOI + IONO + 2IONO2 + 2OIO + 2I2O2 + 3I2O3 + 4I2O4;
LOx : O3 + NO2 + 2NO3 + PAN + PPN + MPAN + HNO4 + 3N2O5 + HNO3 + BrO + HOBr + BrNO2 + 2BrNO3 + MPN + ETHLN + MVKN + MCRHN + MCRHNB + PROPNN + R4N2 + PRN1 + PRPN + R4N1 + HONIT + MONITS + MONITU + OLND + OLNN + IHN1 + IHN2 + IHN3 + IHN4 + INPB + INPD + ICN + 2IDN + ITCN + ITHN + ISOPNOO1 + ISOPNOO2 + INO2B + INO2D + INA + IDHNBOO + IDHNDOO1 + IDHNDOO2 + IHPNBOO + IHPNDOO + ICNOO + 2IDNOO + MACRNO2 + ClO + HOCl + ClNO2 + 2ClNO3 + 2Cl2O2 + 2OClO + O + O1D + IO + HOI + IONO + 2IONO2 + 2OIO + 2I2O2 + 3I2O3 + 4I2O4;
PCO : CO;
LCO : CO;
PSO4 : SO4;
LCH4 : CH4;
PH2O2 : H2O2;
```

**Comment by RolfSander** [comment]
Regarding the scanner warnings: If we don't know who made these changes,
I suggest we simply keep ScanError as it was in version 2.2.3.

However, we may want to make the error message a bit more user-friendly.
Currently, you only get the equation number. We could print out the
whole equation.

**Comment by RolfSander** [comment]
I think the `dev` branch that Bob refers to is now the branch called
`gc_dev`. Right? We can probably call it a "feature branch" and bring it
in at a later stage, as Bob suggests.

**Comment by RolfSander** [comment]
My high values of `MAX_EQN` and `MAX_SPECIES` can be quite a challenge for
machines that don't have enough memory. Let's stick to 1023 for now...

**Review by yantosca — APPROVED** [review]
This all looks good.  Thanks everyone!

**Pull request merged**
