### PR TITLE
MCM

### PR DESCRIPTION
**Pull request by RolfSander**
see https://github.com/KineticPreProcessor/KPP/issues/4

### CODE REVIEW

**Review by yantosca — APPROVED** [review]
This looks good to merge.  I will merge into dev. then make sure we change the version numbers etc, then merge into main.

**Comment by RolfSander** [comment]
Thanks, @yantosca!

I think we're ready for the 3.1.0 release.

I still want to solve the problem with the preprocessor style comments
(https://github.com/KineticPreProcessor/KPP/issues/91) but that's not
urgent...

**Comment by yantosca** [comment]
Thanks @RolfSander.  I'll release today.

**Comment by RolfSander** [comment]
Great, thanks for releasing 3.1.0!

**Pull request merged**
